theme: jekyll-theme-minimal
title: CS 3041 Design Manifesto
description: Ilana Zeldin
avatar: "/ilana3.png"
navbar-text-col: "#FF1493"

footer-col: "#FF1493"
footer-text-col: "#FF1493"
footer-link-col: "#FF1493"

link-col: "#FF1493"
hover-col: "#E135D0"

