theme: jekyll-theme-minimal
title: CS 3041 Design Manifesto
description: Ilana Zeldin

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

avatar: "/ilana3.png"
navbar-text-col: "#FF1493"

footer-col: "#FF1493"
footer-text-col: "#FF1493"
footer-link-col: "#FF1493"

link-col: "#FF1493"
hover-col: "#E135D0"

