theme: jekyll-theme-minimal
title: CS 3041 Design Manifesto
description: Ilana Zeldin

<img width="189" alt="ilana3" src="https://user-images.githubusercontent.com/6757445/39439043-4462347a-4c74-11e8-8651-f8649faa769b.PNG">
